# Generated by Django 3.1.3 on 2020-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='executed_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
