# Generated by Django 3.1.3 on 2020-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='executed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
